### PR TITLE
Reorganize the github repository.

### LINKED ISSUE #1503: reorganize repository into code and sample modules

### PR DESCRIPTION
**Pull request by mikereiche**
Reorganize the github repository to allow addition of a sample/test application
that consumes spring-data-couchbase.

Closes #1503.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACOUCH).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by mikereiche** [comment]
Hi @mp911de  - The main purpose is to include a spring-boot application that consumes spring-data-couchbase. We had an issue last year where I merged a contributed PR that removed a public api that broke the application initialization and we didn't catch that because we only have tests that have application initialization via @SpringJUnitConfig(Config.class) instead of a real spring-boot application.

**Comment by mp911de** [comment]
Having a dependency to Spring Boot does not really work because of the dependency graph. Conceptually, Boot depends on Data and introducing a Boot dependency into a Data repository breaks the separation. If you want to verify the integration in an automated way, I suggest setting up a separate repository that consumes the latest data snapshots.

**Comment by mikereiche** [comment]
Ugh.  That's kind of important. Thanks.

**Comment by mikereiche** [comment]
> Having a dependency to Spring Boot does not really work because of the dependency graph

The intent is to not have a &lt;module&gt; in the parent pom.xml for the sample application - and therefore no cyclic dependency.  It would just be located in the same repository, so when cloning spring-data-couchbase, the sample app would be available.   It's true that the same could be accomplished in a separate repository, but this would be more convenient and more likely to be used by someone working on spring-data-couchbase.

**Pull request merged**
