### PR TITLE
DATACOUCH-159: Improve performance of decoding of longs

### PR DESCRIPTION
**Pull request by Aloren**
…a lot of longs inside

### CODE REVIEW

**Comment by daschl** [comment]
thanks for the PR! In general, did you sign the spring CLA? 

also @simonbasle did some work on that in the java client, so he is well suite to take that further :)

**Comment by Aloren** [comment]
@daschl Hi, yes. I've just signed it. My confirmation number is 135920150827075416.
Thanks.

**Comment by simonbasle** [comment]
thanks for the PR and DATACOUCH-159 analysis!

we had a similar issue in the SDK itself, and I think the solution we put into place is even wider and simpler :smile: see https://github.com/couchbase/couchbase-java-client/commit/52fb7d851e5ef055519f158af494969862455587

would you mind changing your implementation to align with that? ie. in `JacksonTranslationService.decodePrimitive()`:
 * no need for `getNumber` method, use `getNumberValue()` instead
 * replace `getValueAsDouble()` with `getDoubleValue()`
 * replace `getValueAsBoolean()` with `getBooleanValue()`

by the way, any particular reason you implemented this on top of a branch derived from `1.2.x` instead of the latest 1.x branch / master?

**Comment by Aloren** [comment]
@simonbasle thanks. I've just fixed according to your comments.
My fix is based on top of 1.2.x version since this version which supports custom class keys for CouchbaseDocuments (by supplying custom converter). I suppose that the reason is in spring-data-common, in which implementation of key conversion was changed. So in the newew versions of spring-data-couchbase it is not possible to do like that:

```
@Document
  class Doc{

    @Id
    private MyCustomKey id;
```

**Comment by simonbasle** [comment]
one last code change and this should be good to go ;) (see my comments)

also, I will need to cherry-pick this PR into branches `1.2.x`, `2.0.x` and `master` then close it manually, so I'd prefer to have just one squashed commit, can you do that?

**Comment by simonbasle** [comment]
(:+1: on the code now, thanks for fixing)

**Comment by Aloren** [comment]
@simonbasle done. thank you :)

**Comment by olivergierke** [comment]
Thanks for the contribution @Aloren. That's merged with minor polishing to master and 1.3.x. 1.2.x is not maintained anymore.

@simonbasle - I guess the forward-port to 2.0 is a bit more involved, so I'll leave that one to you :).

**Comment by simonbasle** [comment]
@olivergierke @Aloren ported to `2.0.x` as well :cake:

**Comment by simonbasle** [comment]
Closing this since the change was merged into supported versions
@Aloren from your more recent PR (that I'll try to look at today or tomorrow btw), looks like your baseline is now `1.3.x`, can you confirm?

**Comment by Aloren** [comment]
@simonbasle yes, that is correct

**Comment by simonbasle** [comment]
awesome, you'll benefit from the improvements of `1.3.x`and you'll be able to use your contribution from an official release :smile: :tada:

**Pull request closed without merging**
