### PR TITLE
DATACOUCH-180 - Allow named parameters in inline N1QL queries

### PR DESCRIPTION
**Pull request by simonbasle**
@daschl can you review this? :bow:

### CODE REVIEW

**Comment by daschl** [comment]
one minor comment, otherwise :+1:

**Comment by simonbasle** [comment]
I wanted to limit the syntax for placeholders to syntaxes that are native to N1QL but still make sense in the Spring Data world.

Both `$1` and `$name` syntaxes are native to N1QL and AFAIK accepted (although maybe not canonical) syntaxes in Spring Data. The `$name` would need a `@Param("name")` annotation.

@olivergierke can you confirm this looks good to you as well?

**Comment by simonbasle** [comment]
updated the PR, detection of the placeholder type is now done by analyzing the query and mixing named and positional placeholders is now throwing an `IllegalArgumentException` at repository creation.

**Comment by daschl** [comment]
:+1:

**Pull request merged**
