### PR TITLE
DATACOUCH-169 - Automatic index management

### PR DESCRIPTION
**Pull request by simonbasle**
Main indexes (ie indexes that can be used by repositories to retrieve ALL the documents of a particular entity type) are covered.

Repository interfaces can be annotated with an annotation for each type of main index that can be automatically created.

The IndexManager is responsible for creating said indexes (potentially skipping creation if an index is already in place).

Added doc and integration test.

Renamed package core.view to core.query since it now contains various non-view related annotations and classes.

### CODE REVIEW

**Comment by simonbasle** [comment]
ready for review @daschl

**Comment by simonbasle** [comment]
@daschl made some modifications re your comments (N1qlSecondaryIndexed should not deal with PRIMARY at all, it should be possible to toggle off the feature depending on the context at runtime)

**Comment by simonbasle** [comment]
just rebased over #80

**Comment by simonbasle** [comment]
@daschl ready for review :book:

**Comment by daschl** [comment]
reviewed the latest xml changes, :+1:

**Comment by simonbasle** [comment]
rebased and squashed to be merged in `2.0.x`

**Pull request merged**
