### PR TITLE
DATACOUCH-211 - Applying sort that's passed in via the Pagenate object

### PR DESCRIPTION
**Pull request by longwatertech**

### CODE REVIEW

**Comment by simonbasle** [comment]
This looks good to me but is most likely to cause merge conflicts with #105, so we'll work on getting the latest in first.
Once you've reworked #105 and I've merged it to master, will you be able to rebase this on master and fix any conflict that may arise?

**Comment by longwatertech** [comment]
Thanks again @simonbasle. I'll absolutely happy to sort out the rebase and conflict resolution once #105 is merged. Thanks.

**Comment by longwatertech** [comment]
@simonbasle - rebased on master and updated to fix test. Should be good now.

**Comment by simonbasle** [comment]
thanks again for both PRs, this has been merge :wink:

**Pull request merged**
