### PR TITLE
DATACOUCH-148 - Allow to configure repository queries staleness globally

### PR DESCRIPTION
**Pull request by simonbasle**
The staleness to apply on generated view queries (`Stale`) and N1QL queries (`ScanConsistency`) can now be chosen via the configuration.

It is accessed from the `CouchbaseOperations` interface but is applied to the template only. In xml, the `viewStaleness` and `n1qlStaleness` attributes are configurable on the `couchbase:template` element (string value of the enums to be passed in).

### CODE REVIEW

**Comment by simonbasle** [comment]
@daschl please code review :book:, @olivergierke I'd like your take on that as well (maybe there's a better "Spring Way ©" to do it :panda_face:)

**Comment by daschl** [comment]
@simonbasle would it be possible to converge on a sdc-based enum for consistency which in turn translates over into view and n1ql staleness params? I know we dont have that in the SDK, but I was thinking for a user perspective it might help them

**Comment by daschl** [comment]
Like "Consistency.STRONG or EVENTUAL" or something

**Comment by simonbasle** [comment]
@daschl added a `Consistency` enum that does just that. Also edited the documentation

**Comment by simonbasle** [comment]
squashed in preparation for cherry-picking into 2.0.x

**Pull request merged**
