### PR TITLE
DATACOUCH-161 - Support repos with different buckets

### PR DESCRIPTION
**Pull request by simonbasle**
Added a configuration bean that allows to express what `CouchbaseOperations` each repository should use, individually or by domain type.

### CODE REVIEW

**Comment by simonbasle** [comment]
pinging @daschl for code review :computer: :eyes:

**Comment by simonbasle** [comment]
also @christophstrobl and/or @olivergierke I'd like your quick review too.
this is the best way I found how to do it (the `@EnableCouchbaseRepositories` cannot be repeated and there's no practical ways of declaring such a mapping on it that I could think of, since annotations are limited a lot, String/enums/constant values/... and single depth arrays of these)

**Comment by daschl** [comment]
@simonbasle looks good to me, but I'd prefer if @christophstrobl and/or @olivergierke  can sign this too, so we are doing it the spring way ;)

**Comment by daschl** [comment]
:+1:

**Comment by simonbasle** [comment]
squashed and rebased commits, now merging

**Pull request merged**
