### PR TITLE
DATACOUCH-588 - Implement pageable and realign with other spring-data projects

### PR DESCRIPTION
**Pull request by mikereiche**
This is my second pull-request for this. I've removed the unrelated bug fixes.

This implements pageable for non-reactive queries and
realigns reactive queries with other spring-data projects
to facilitate the implementaion of pageable (done) and other
types of queries such as projection and distinct (not yet
done)

The isDelete() etc. methods in CouchbaseQueryMethod are called by methods of the same names in AbstractCouchbaseQuery. 

The ReactivePagedExecution is commented out - they don't seem like the best implementations. Mark suggested following the pattern in Mongo and Cassandra.

Edit: I just noticed I haven't updated the authors and copyright notices as required.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACOUCH).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by tchlyah** [comment]
Hello, do you have any ETA for merging this issue ? The issues fixed in this PR are blocking the whole Spring Boot 2.3 upgrade for jhipster. See https://github.com/jhipster/generator-jhipster/issues/12300

**Comment by mikereiche** [comment]
> Hello, do you have any ETA for merging this issue ? The issues fixed in this PR are blocking the whole Spring Boot 2.3 upgrade for jhipster. See [jhipster/generator-jhipster#12300](https://github.com/jhipster/generator-jhipster/issues/12300)

@tchlyah I'm looking at pulling the scanConsistency fix into it's own branch so it can be committed sooner.

**Comment by tchlyah** [comment]
Hello @mikereiche, can you please resolve the conflicts? We would like to see that merged ASAP! Thanks a lot

**Comment by mp911de** [comment]
Please let's move this PR into the next version (4.2) as right now, were post RC2 for 4.1 and the amount of changes bears quite some risk. Typically, a release should be feature complete before entering the RC phase and after the last release candidate, we allow only documentation changes, bugfixes, polishing, test refactorings, and such.

**Comment by mikereiche** [comment]
superseded

**Pull request closed without merging**
