### PR TITLE
DATACOUCH-179 : with Integration Test 

### PR DESCRIPTION
**Pull request by MLabusquiere**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACOUCH).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by MLabusquiere** [comment]
This pr continues #132 of @zakariaeMahla with several improvements : 

- Add integration tests
- @N1qlSecondaryIndexed supports now @TypeAlias

**Comment by MaBeuLux88** [comment]
+1 for this PR

**Comment by Ssunnyy** [comment]
I used two bucket (userBucket, couchbaseBucket). When I created public interface, UserRepository, extends, CrudRepository<UserModel, and String>, how do I specify which UserModel bucket is in?

**Comment by MLabusquiere** [comment]
This is not the right place to ask this question. Please look at the documentation working with two buckets of the official documentation that I advice you to read fully : https://docs.spring.io/spring-data/couchbase/docs/current/reference/html/#couchbase.repository.multibucket

**Comment by Ssunnyy** [comment]
I have another problem, the previous project did not use Spring data couchbase, and there is no _class: property in doument. Now, how do I use the Spring data couchbase framework to query the data in the previous database?. I tried findByTitle and other property query methods to return null, but using findById to check the data, I need help, I hope you can get your advice.

**Comment by MLabusquiere** [comment]
@olivergierke I don't understand why you closed this pull request. Can we have an explanation.
There is in my opinion valuable code, from @zakariaeMahla @MaBeuLux88 and myself which is a production need in our customer and answer to a spring data couchbase jira.

**Comment by olivergierke** [comment]
I didn't deliberately close it, we just removed a the branches for an escape hatch release train that we now don't need anymore as we have the Kay GA release out. Feel free to just resubmit the PR as is based on the Ingalls or Kay branch.

**Pull request closed without merging**
