### PR TITLE
Couchbase 3.0.0 Support / Migration to Java SDK 2.0

### PR DESCRIPTION
**Pull request by jloisel**
I have done the code migration to the Couchbase Java Client 2.0 which supports Couchbase 3.0.0 (recently released). I have also upgraded:
- Spring to 4.1.1.RELEASE,
- Jackson to 2.4.3.

All JUnits are passing excepting this last one:
SimpleCouchbaseRepositoryTests.findAll()

### CODE REVIEW

**Comment by kschulst** [comment]
Anybody have a status on this?

**Comment by daschl** [comment]
@kschulst we are working on it, but the 2.0 port is quite some work. We don't have a specific timeline, although we want to get something out in Q2 - would that be okay?

**Comment by kschulst** [comment]
It might not be possible... but just a suggestion: if there are any possibilities to release a "preview-version" that uses the 2.x SDK before _all_ snags are resolved, that would be nice. It could also help facitilate more users to contribute if the 2.x move is divided up a bit.

Waiting until Q2 (+delays ;)) seems like a long time. At least for our use case, we need to look at options. In particular, we need access to the Atomic operations (counter).

**Comment by kschulst** [comment]
But let me know if there are things I can do to contribute

**Comment by daschl** [comment]
@kschulst sounds great.. what about if you just wire up the new SDK manually? In the worst case, 1.4 and 2.1 can be used side by side because they are different artifacts.

I'll see what I can do in the near term and will update this ticket..

**Comment by kschulst** [comment]
That was actually my idea :) Think that will work out just fine, I was just investigating the package structure and noticed that there are no clashes.

Could be an idea to post some info about this approach if it works out well. This will make it easier for sdk2-waiters to swallow the Q2-wait.

Thanks :)

**Comment by daschl** [comment]
@kschulst it's great to see more traction on this project. I've been quite busy with 2.x SDKs recently, but now that is out of the door and stabilising we want to refocus our efforts on up the stack integration (which includes the rewrite. It just will take some time to be done properly and also we want to make N1QL a first class citizen so that the upcoming couchbase server already has great @Query support with N1QL and all that...)

**Comment by kschulst** [comment]
For other readers of this thread that might want to do something similar... add the following spring config to wire in SDK2 explicitly:

    @Bean(destroyMethod = "disconnect")
    public Cluster couchbaseClusterSdk2() {
        return CouchbaseCluster.create(host);
    }

    @Autowired
    @Bean(destroyMethod = "close")
    public Bucket couchbaseBucketSdk2(Cluster cluster) {
        return cluster.openBucket(bucketName, bucketPassword);
    }

(And make sure to include the sdk2 dependency, e.g. using maven:
        <dependency>
            <groupId>com.couchbase.client</groupId>
            <artifactId>java-client</artifactId>
            <version>2.1.x</version>
        </dependency>
)

**Comment by jloisel** [comment]
Great that you work on this. As we don"t have had any feedback for a while on this, we finally did our own API wrapping the Java 2.1 SDK with both Async and Sync repositories. Here are the main interfaces.

AsyncRepository:
```
/**
 * An {@link Observable} repository.
 * 
 * @author jerome
 *
 * @param <T> type of the persisted entity
 */
public interface AsyncRepository<T extends ImmutableIdEntity> {

  /**
   * Returns whether an entity with the given id exists.
   * 
   * @param id must not be {@literal null}.
   * @return true if an entity with the given id exists, {@literal false} otherwise
   * @throws IllegalArgumentException if {@code id} is {@literal null}
   */
  Observable<Boolean> exists(String id);

  /**
   * Finds an element by its id.
   * 
   * @param id identifier
   * @return an {@link Observable} emitting the element if found
   */
  Observable<T> findOne(String id);

  /**
   * Saves an entity into the repository.
   * 
   * @param entity entity to save
   * @return an {@link Observable} emitting the saved element
   */
  Observable<T> save(T entity);

  /**
   * Saves an element into the repository.
   * 
   * @param entities entities to save
   * @return an {@link Observable} emitting the saved element
   */
  Observable<T> save(Iterable<T> entities);

  /**
   * Finds all the elements.
   * 
   * @return an {@link Observable} which emits the elements found
   */
  Observable<T> findAll();

  /**
   * Finds all the elements with ids within the given list of ids.
   * 
   * @param ids list of ids to retrieve
   * @return an {@link Observable} which emits the elements found
   */
  Observable<T> findAll(Iterable<String> ids);

  /**
   * Query a database view.
   * 
   * @param query query to execute
   * @return an {@link Observable} which emits the results
   */
  Observable<T> queryView(ViewQuery query);

  /**
   * Delete a document by its id.
   * 
   * @param id id of the document to delete
   * @return an {@link Observable} emitting the id of the deleted document
   */
  Observable<String> delete(String id);

  /**
   * Delete a document by its id.
   * 
   * @param id id of the document to delete
   * @return an {@link Observable} emitting the id of the deleted document
   */
  Observable<String> delete(T entity);

  /**
   * @return an {@link Observable} emitting all the ids of the deleted documents
   */
  Observable<String> deleteAll();
}
```

@daschl We can provide the source code of our implementation if you need to. Although, it's not as powerful as Spring Data (manual factory, interface to be implemented on entities).

**Comment by daschl** [comment]
@jloisel awesome, great to hear :) .. if I'm stuck at some part I'll definitely ping you..we were thinking about doing a CrudRepository and a ObservableRepository.

In theory with N1QL we can even pursue the PagingAndSortingRepository.

**Comment by jloisel** [comment]
I've shared the code here:
https://github.com/jloisel/reactive-couchbase

Not perfect, but suits our needs. :)

**Comment by rajeshbasawa** [comment]
Do we have the tentative date when will we have Spring data Couchbase be ready to use Couchbase 2.1 SDK ?
Any preview release would also help as we are stuck with Couchbase SDK 2.1 and SDC which doesn't use Observable.

**Comment by daschl** [comment]
@rajeshbasawa hi, we are targeting a first milestone release in april for now, and then get it on the fowler+1 release train.

**Comment by olivergierke** [comment]
That's gonna be [Gosling](https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Gosling). I'd suggest to create a ticket in JIRA, create a feature branch for that ticket and merge the PR into that branch. That way, we can already produce nightly snapshots of that support for alpha testing.

**Comment by suyambuganesh** [comment]
Anybody have a status on this?

**Comment by daschl** [comment]
@suyambuganesh indeed! @simonbasle has nearly finished the initial port and we will soon be tracking a 2.0 release from a feature branch. Since gosling is already rolling, we are planning to officially put it back in gosling+1, but there will be separate artefacts to download and try for sure in the meantime.

**Comment by suyambuganesh** [comment]
@daschl perfect, thanks.

**Comment by daschl** [comment]
Everyone interested in this topic, here is the plan of action by now: we are going to have a preview release end of july wich will have all that was supported in the 1.x, as well as new cool things on top of N1QL. 

If you are curious, the initial bump will soon be merged into the 2.0.x branch, where all the progress will be done. 

Once gosling is done, this will be merged into master and part of the next release train, which will probably be a shorter cycle. This is not set in stone, but we plan for a GA end of october or so (but with pre-releases in between so you can work with it).

**Comment by daschl** [comment]
Oh and for completeness, this one is superseeded by #51. Big thanks to everyone for the effort, especially @jloisel.

**Comment by rajeshbasawa** [comment]
@daschl Just wondering if Spring data 2.0 going to support APIs based on RxJava. Didn't see anything related to that in commits.

**Comment by daschl** [comment]
Yes it is planned! Stay tuned :)

**Comment by jloisel** [comment]
:+1:

**Pull request closed without merging**
