### PR TITLE
DATACOUCH-110 - Include the customSimpleTypes from Converters in SimpleTypeHolders

### PR DESCRIPTION
**Pull request by lyngaas**

### CODE REVIEW

**Comment by daschl** [comment]
@lyngaas thanks much for your contribution, I'll take a look soon :)

**Comment by daschl** [comment]
@lyngaas did you sign the CLA? :)

**Comment by lyngaas** [comment]
@daschl the CLA is now signed :)

**Comment by daschl** [comment]
thanks!

**Comment by daschl** [comment]
merged in, thanks!

**Pull request closed without merging**
